

app:
  version: @project.version@
  name: @project.name@

logging:
  level:
    com:
      sischi: debug

spring:
  profiles:
    include: parameter-info

selvebridge:
  deadlock:
    threshold: 60
    watchdogInterval: 30
  connection:
    serialPort: /dev/ttyUSBX
    reconnectInterval: 15
    watchdogInterval: 60
  mqtt:
    enabled: false
    broker: hostname
    protocol: tcp
    port: 1883
    qos: 0
    retain: true
    topicPrefix: "selve"
    