

app:
  version: @project.version@
  name: @project.name@

logging:
  level:
    com:
      sischi: debug

selvebridge:
  deadlock:
    threshold: 60
    watchdogInterval: 30
  connection:
    serialPort: /dev/ttyUSB0
    reconnectInterval: 15
    watchdogInterval: 60
  mqtt:
    enabled: false
    broker: hostname
    protocol: tcp
    port: 1883
    qos: 0
    retain: true
    prefix: "selve"
    