version: "3.6"

services:
  selvebridge:
    build: .
    image: adoptopenjdk-8
    container_name: selve-bridge

    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    
    ports:
      - "8080:8080"
    
    volumes:
      - ./app:/app
    
    working_dir: /app
    command: /app/start.sh

